### ISSUE TITLE
Layout - Create the given layouts using LinearLayout

### ISSUE THREAD

**Issue by thsaravana** [divyap7/AndroidPlayground#1]
<img width="271" alt="screen shot 2018-05-29 at 18 56 42" src="https://user-images.githubusercontent.com/11502338/40661747-2b6750e4-6372-11e8-81a6-e108bab5f7fc.png">
<img width="269" alt="screen shot 2018-05-29 at 18 55 32" src="https://user-images.githubusercontent.com/11502338/40661749-2b99f062-6372-11e8-98e9-38a89ad84baa.png">
<img width="272" alt="screen shot 2018-05-29 at 18 57 10" src="https://user-images.githubusercontent.com/11502338/40661750-2bcf15bc-6372-11e8-9e20-9972d9dede65.png">
<img width="267" alt="screen shot 2018-05-29 at 18 54 49" src="https://user-images.githubusercontent.com/11502338/40661751-2c091ab4-6372-11e8-9996-e9e089d0dd30.png">
<img width="272" alt="screen shot 2018-05-29 at 18 54 20" src="https://user-images.githubusercontent.com/11502338/40661752-2c3abca4-6372-11e8-82e5-8f6133fd55e1.png">

**Comment by divyap7** [comment]
![screenshot_20180531-002528](https://user-images.githubusercontent.com/32665765/40852563-7225b35e-65e8-11e8-8fb2-25f3221997bf.png)
![screenshot_20180531-002630](https://user-images.githubusercontent.com/32665765/40852566-732005ca-65e8-11e8-888f-3e11fe6bc985.png)
![screenshot_20180531-002735](https://user-images.githubusercontent.com/32665765/40852579-7edb98de-65e8-11e8-87ee-7b4e090d3e99.png)
![screenshot_20180601-215955](https://user-images.githubusercontent.com/32665765/40852580-7f67cd7c-65e8-11e8-8764-a42d9fccb78e.png)
![screenshot_20180601-220326](https://user-images.githubusercontent.com/32665765/40852582-830f5102-65e8-11e8-8163-6a2060600cf4.png)

**Comment by thsaravana** [comment]
I saw the Layout files you created. There are too many warnings. Fix all of them.
