### ISSUE TITLE
Layout - Create the layouts using RelativeLayout

### ISSUE THREAD

**Issue by thsaravana** [divyap7/AndroidPlayground#2]
<img width="271" alt="screen shot 2018-05-29 at 18 56 42" src="https://user-images.githubusercontent.com/11502338/40661787-4840c952-6372-11e8-8549-ad15b6ef592a.png">
<img width="269" alt="screen shot 2018-05-29 at 18 55 32" src="https://user-images.githubusercontent.com/11502338/40661788-48be157e-6372-11e8-98ca-74313c7fabb2.png">
<img width="272" alt="screen shot 2018-05-29 at 18 57 10" src="https://user-images.githubusercontent.com/11502338/40661789-492246b6-6372-11e8-8d26-d3febaa461ef.png">
<img width="267" alt="screen shot 2018-05-29 at 18 54 49" src="https://user-images.githubusercontent.com/11502338/40661790-497ebc0c-6372-11e8-8d20-d13944560d08.png">
<img width="272" alt="screen shot 2018-05-29 at 18 54 20" src="https://user-images.githubusercontent.com/11502338/40661792-49e2f1b8-6372-11e8-9dd4-1f6d5cd7338d.png">

**Comment by divyap7** [comment]
![screenshot_20180601-230522](https://user-images.githubusercontent.com/32665765/40856067-1bbfb5d0-65f4-11e8-8f4d-d183522ede2e.png)
![screenshot_20180601-231554](https://user-images.githubusercontent.com/32665765/40856068-1d04f680-65f4-11e8-9f88-e87415a9b95c.png)
![screenshot_20180601-232311](https://user-images.githubusercontent.com/32665765/40856069-1d8e6924-65f4-11e8-89be-4d8f7d4aa173.png)
![screenshot_20180601-232608](https://user-images.githubusercontent.com/32665765/40856070-1de1fd82-65f4-11e8-831c-df5ee93b61b6.png)
![screenshot_20180601-232928](https://user-images.githubusercontent.com/32665765/40856071-1e34a6d6-65f4-11e8-8658-fcd422c85061.png)

**Comment by thsaravana** [comment]
There is an `odd` gap between the two horizontal buttons. Fix that.

**Comment by thsaravana** [comment]
I saw the Layout files you created. There are too many warnings. Fix all of them.
