### ISSUE TITLE
Do the same layouts in #2 but using ConstraintLayout

### ISSUE THREAD

**Issue by thsaravana** [divyap7/AndroidPlayground#3]
I am sick and won't be available today. 
1. Do the same 5 layouts in #2 using ConstraintLayout
2. There should be no warnings

**Comment by divyap7** [comment]
![screenshot_20180605-231605](https://user-images.githubusercontent.com/32665765/40995204-10cafc68-691c-11e8-8105-dbaa519d4ade.png)
![screenshot_20180605-233206](https://user-images.githubusercontent.com/32665765/40995205-1125c058-691c-11e8-8ceb-5f7d9e289794.png)
![screenshot_20180605-234157](https://user-images.githubusercontent.com/32665765/40995207-11681f20-691c-11e8-9d7f-e2fbe4953b3a.png)
![screenshot_20180605-234427](https://user-images.githubusercontent.com/32665765/40995209-11acd390-691c-11e8-93b3-24428891d667.png)
![screenshot_20180605-235253](https://user-images.githubusercontent.com/32665765/40995210-11f48014-691c-11e8-9860-be48303f6adc.png)

**Comment by thsaravana** [comment]
<img width="220" alt="screen shot 2018-06-06 at 07 24 17" src="https://user-images.githubusercontent.com/11502338/41011473-b0cc2488-695a-11e8-9c56-c2907b3528b3.png">
<img width="374" alt="screen shot 2018-06-06 at 07 24 28" src="https://user-images.githubusercontent.com/11502338/41011474-b10376b8-695a-11e8-8bd6-a5f6aec15953.png">

Never hardcode the dimension values. I changed the layout from Portrait to Landscape and everything fell apart. Fix it. For all Constraint layout. Start with `constraintlayout_4.xml`
