### ISSUE TITLE
Questions in Layouts

### ISSUE THREAD

**Issue by thsaravana** [divyap7/AndroidPlayground#4]
1. What is the difference between `wrap_content` and `match_parent` ?
2. When you type `android:layout_width="342dp"` - what does that `dp` mean?
3. What is the difference between `sp` and `dp` ?
4. Why is `android:layout_width="342dp"` considered bad? i.e, specifying in `dp`s are considered bad. Why?
5. What is difference between `android:hint` and `android:text` ?

**Comment by divyap7** [comment]
Answer:1 
Wrap content: Size depends on the content of the view
Match parent: The size of the view will be same as the parents size

Answer:2
dp - density independent pixel , the dimensions of the view will be adjusted to the density of the phone screen

Answer:3
We can use dp for all dimensions but sp for font size as they adjust for both the screen density and the user's preference.

Answer:4 
Specifying in dp is to not worry about different screen density , but devices like tabs have large screen size but a smaller density so its bad 

Answer:5
android:text - sets text to the element
android:hint - Used in editText view. Will be displayed when there is no text, like a placeholder

**Comment by thsaravana** [comment]
Good work!
